server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://10.1.0.125:3306/neil?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dbcp2:
      max-total: 500
      max-idle: 5
      max-wait-millis: 60000
      min-idle: 1
      min-evictable-idle-time-millis: 1800000
      test-on-borrow: true
      test-while-idle: true
      initial-size: 0